version: '3.5'

services:
  server:
    image: node:latest
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
    working_dir: /app
    command: bash -c "npm i && npm start"
    environment:
      - HARVARD_URL=https://api.harvardartmuseums.org
      - API_KEY=${API_KEY}

  client:
    image: node:latest
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: bash -c "npm i && npm start"
    environment:
      - CYPRESS_CACHE_FOLDER=/.cache
